### ISSUE TITLE
Cannot resolve theme: api with vuepress 1.0.3

### ISSUE THREAD

**Issue by Linus-Boehm** [sqrthree/vuepress-theme-api#11]
There seems to be some issues with the new vuepress version, at least i can't use the starter kit.
Can anyone provide me in a direction what is going wrong?
```
Error: Cannot resolve theme: api.
    at resolveTheme (/Users/linusboehm/.config/yarn/global/node_modules/@vuepress/core/lib/node/loadTheme.js:109:13)
    at loadTheme (/Users/linusboehm/.config/yarn/global/node_modules/@vuepress/core/lib/node/loadTheme.js:35:17)
    at App.process (/Users/linusboehm/.config/yarn/global/node_modules/@vuepress/core/lib/node/App.js:100:21)
    at dev (/Users/linusboehm/.config/yarn/global/node_modules/@vuepress/core/lib/index.js:14:13)
    at args (/Users/linusboehm/.config/yarn/global/node_modules/vuepress/lib/util.js:35:12)
    at CAC.cli.command.option.option.option.option.option.option.option.option.option.action (/Users/linusboehm/.config/yarn/global/node_modules/vuepress/lib/registerCoreCommands.js:38:23)
    at CAC.runMatchedCommand (/Users/linusboehm/.config/yarn/global/node_modules/cac/dist/index.js:700:38)
    at CAC.parse (/Users/linusboehm/.config/yarn/global/node_modules/cac/dist/index.js:620:18)
    at CLI (/Users/linusboehm/.config/yarn/global/node_modules/vuepress/lib/util.js:23:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```
I tried both local and global install of vuepress & theme

**Comment by JbalTero** [comment]
encountered this too

**Comment by sqrthree** [comment]
Thanks all, A new version [v0.2.3](https://www.npmjs.com/package/vuepress-theme-api/v/0.2.3) has been released to fix this.
