### ISSUE TITLE
Build in error with lastUpdated

### ISSUE THREAD

**Issue by amehat** [sqrthree/vuepress-theme-api#24]
In my project, I have a `docs/fr/authentication.md` page which is in error when I run the` npm run build` command.

The file has the same content as the example https://github.com/sqrthree/vuepress-theme-api-starter-kit/blob/master/docs/2-endpoints/authentication.md.

```
wait Rendering static HTML...
[Vue warn]: Error in render: "TypeError: Cannot read property 'lastUpdated' of undefined"

found in

---> <Page>
       <Anonymous>
         <GlobalLayout>
           <Root>
error Error rendering /fr/authentication.html: false
undefined
TypeError: Cannot read property 'lastUpdated' of undefined
    at 2.server-bundle.js:91:18
    at Array.forEach (<anonymous>)
    at exports.modules.397.exports.getDefaultLocales (Users/{user}/Serveur/oak-dev/node_modules/vuepress-theme-api/helpers/locales.js:26:18)
    at Proxy.lastUpdatedText (node_modules/vuepress-theme-api/layouts/Page.vue:79:0)
    at Proxy.computedGetter (/Users/{user}/Serveur/oak-dev/node_modules/vue/dist/vue.runtime.common.dev.js:4846:15)
    at Proxy.render (Users/{user}/Serveur/oak-dev/node_modules/vuepress-theme-api/layouts/Page.vue?bc7c:1:164)
    at VueComponent.Vue._render (/Users/{user}/Serveur/oak-dev/node_modules/vue/dist/vue.runtime.common.dev.js:3559:22)
    at resolve (/Users/{user}/Serveur/oak-dev/node_modules/vue-server-renderer/build.dev.js:8444:27)
    at waitForServerPrefetch (/Users/{user}/Serveur/oak-dev/node_modules/vue-server-renderer/build.dev.js:8316:3)
    at renderComponentInner (/Users/{user}/Serveur/oak-dev/node_modules/vue-server-renderer/build.dev.js:8455:3)
    at renderComponent (/Users/{user}/Serveur/oak-dev/node_modules/vue-server-renderer/build.dev.js:8412:5)
    at RenderContext.renderNode (/Users/{user}/Serveur/oak-dev/node_modules/vue-server-renderer/build.dev.js:8323:5)
    at RenderContext.next (/Users/{user}/Serveur/oak-dev/node_modules/vue-server-renderer/build.dev.js:2611:23)
    at cachedWrite (/Users/{user}/Serveur/oak-dev/node_modules/vue-server-renderer/build.dev.js:2464:9)
    at renderStringNode$1 (/Users/{user}/Serveur/oak-dev/node_modules/vue-server-renderer/build.dev.js:8540:5)
    at RenderContext.renderNode (/Users/{user}/Serveur/oak-dev/node_modules/vue-server-renderer/build.dev.js:8321:5)
```

If I do an `npm run dev`, the file transpiles correctly.

I tried setting `lastUpdated` to false in config.js, but it doesn't change anything.

**Comment by sqrthree** [comment]
Hi, thanks, a new patch version has been released to solve this error. [v1.0.1](https://www.npmjs.com/package/vuepress-theme-api/v/1.0.1)
